"""Initial migration

Revision ID: da8310edae3f
Revises: d9e42148ca86
Create Date: 2025-10-31 03:15:18.939772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8310edae3f'
down_revision = 'd9e42148ca86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_unique_constraint('_vendor_email_uc', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_constraint('_vendor_email_uc', type_='unique')

    # ### end Alembic commands ###
